export const ADMIN_ACTION = {
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  ADMIN_REGISTER: 'ADMIN_REGISTER',
  GET_ADMIN_INFO: 'GET_ADMIN_INFO',
  CHECK_ADMIN_EMAIL_EXISTS: 'CHECK_ADMIN_EMAIL_EXISTS',
  REFRESH_ADMIN_TOKEN: 'REFRESH_ADMIN_TOKEN',
};
